"""Phase 1F backtest: tune on 2021/22 and 2022/23, then test on 2023/24 to 2025/26.

Writes reports/backtest_1f.md. Run with: uv run python scripts/backtest_1f.py
Spec S8: settings are chosen on the tuning seasons only, never on the test seasons.
"""

from __future__ import annotations

import itertools
import sys
from dataclasses import asdict

import numpy as np
import pandas as pd

from fp import ROOT
from fp.evaluate import backtest as bt
from fp.evaluate import metrics
from fp.ingest.matches import PROCESSED
from fp.models import dixon_coles as dc
from fp.models import elo

TUNE = [2021, 2022]
TEST = [2023, 2024, 2025]
# Run 1 (24 Sep 2026) used ridge [1, 3, 10] and Elo K [15, 20, 30]. Both optima sat
# on the grid edge, so run 2 widened the grid. Choices use the tuning seasons only.
XI = [0.0015, 0.002, 0.003]
RIDGE = [3.0, 10.0, 20.0, 40.0]
ELO_K = [8.0, 10.0, 12.5, 15.0, 20.0]
OUT = ROOT / "reports" / "backtest_1f.md"


def mean_rps(scored: pd.DataFrame, prefix: str) -> float:
    return float(bt.score_1x2(scored, prefix)["rps"].mean())


def tune(matches: pd.DataFrame) -> tuple[dc.DCParams, elo.EloParams, pd.DataFrame]:
    rows = []
    for xi, ridge in itertools.product(XI, RIDGE):
        cfg = bt.Config(seasons=TUNE, dc=dc.DCParams(xi=xi, ridge=ridge))
        s = bt.attach_outcomes_and_market(bt.run(matches, cfg), matches)
        rows.append({"model": "dc", "xi": xi, "ridge": ridge, "rps": mean_rps(s, "dc")})
        print(f"tune dc xi={xi} ridge={ridge}: {rows[-1]['rps']:.5f}", flush=True)
    for k in ELO_K:
        cfg = bt.Config(seasons=TUNE, elo=elo.EloParams(k=k))
        s = bt.attach_outcomes_and_market(bt.run(matches, cfg), matches)
        rows.append({"model": "elo", "k": k, "rps": mean_rps(s, "elo")})
        print(f"tune elo k={k}: {rows[-1]['rps']:.5f}", flush=True)
    grid = pd.DataFrame(rows)
    best_dc = grid[grid.model == "dc"].sort_values("rps").iloc[0]
    best_elo = grid[grid.model == "elo"].sort_values("rps").iloc[0]
    return (dc.DCParams(xi=float(best_dc.xi), ridge=float(best_dc.ridge)),
            elo.EloParams(k=float(best_elo.k)), grid)


def table(frame: pd.DataFrame) -> str:
    cols = list(frame.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for r in frame.itertuples(index=False):
        lines.append("| " + " | ".join(
            f"{v:.4f}" if isinstance(v, float) else str(v) for v in r) + " |")
    return "\n".join(lines)


def main() -> int:
    matches = pd.read_parquet(PROCESSED / "matches.parquet")
    dc_params, elo_params, grid = tune(matches)
    print("chosen:", asdict(dc_params), asdict(elo_params), flush=True)

    cfg = bt.Config(seasons=TEST, dc=dc_params, elo=elo_params)
    scored = bt.attach_outcomes_and_market(bt.run(matches, cfg), matches)
    models = ["base", "elo", "dc", "mkt_sharp", "mkt_avg_close", "mkt_avg_pre"]

    sections = []
    for (lg, season), g in scored.groupby(["league", "season"]):
        sections.append(f"### {lg} {season}/{(season + 1) % 100:02d}\n\n"
                        + table(bt.summary(g, models)))
    overall = bt.summary(scored, models)

    common = scored.dropna(subset=[f"mkt_sharp_{k}" for k in ("home", "draw", "away")])
    rps = {m: bt.score_1x2(common, m)["rps"].to_numpy() for m in ("base", "elo", "dc",
                                                                  "mkt_sharp")}
    diffs = []
    for other in ("base", "elo", "mkt_sharp"):
        d = rps["dc"] - rps[other]
        lo, hi = bt.paired_ci(d)
        diffs.append({"comparison": f"dc minus {other}", "mean_rps_diff": float(d.mean()),
                      "ci_low": lo, "ci_high": hi})

    ou = scored.dropna(subset=["mkt_sharp_over_2_5"])
    y = ou["over_2_5"].to_numpy()
    ou_rows = [{"model": m, "n": len(ou),
                "log_loss": float(metrics.binary_log_loss(ou[c].to_numpy(), y).mean()),
                "brier": float(metrics.binary_brier(ou[c].to_numpy(), y).mean())}
               for m, c in (("base", "base_over_2_5"), ("dc", "dc_over_2_5"),
                            ("mkt_sharp", "mkt_sharp_over_2_5"))]

    top_pick = float((scored[["dc_home", "dc_draw", "dc_away"]].to_numpy().argmax(1)
                      == scored["outcome"]).mean())
    red_flag = top_pick > 0.60
    text = f"""# Phase 1F backtest

Generated by `scripts/backtest_1f.py`. Walk-forward: each match is predicted at the
daily run that would have locked it, from results known by then (leakage check passed).

- Tuning seasons: {', '.join(f'{s}/{(s + 1) % 100:02d}' for s in TUNE)}.
- Test seasons: {', '.join(f'{s}/{(s + 1) % 100:02d}' for s in TEST)}.
- Chosen Dixon-Coles settings: decay xi = {dc_params.xi} per day \
(half-life {np.log(2) / dc_params.xi:.0f} days), ridge = {dc_params.ridge}.
- Chosen Elo K = {elo_params.k}.
- Honesty note: run 1 used a narrower grid whose best settings sat on its edge \
(ridge 10, Elo K 15). Run 2, this report, widened the grid and chose again from \
the tuning seasons only. The test seasons have therefore been scored twice. \
Run 1 test result: dc RPS 0.1974, elo 0.1980, sharp market 0.1912.
- Models: `base` = league frequencies over the last three seasons; `elo`; `dc` = \
Dixon-Coles; `mkt_sharp` = Pinnacle closing odds, or Betfair Exchange closing \
after Pinnacle's data ends in Jan 2026; `mkt_avg_close` and `mkt_avg_pre` = market \
average at close and at the Friday or Tuesday snapshot. All odds de-margined by the \
power method. Lower RPS, log loss, and Brier are better.

## 1X2, all test seasons, both leagues

{table(overall)}

## Differences with 95% paired bootstrap intervals (RPS, negative means dc is better)

{table(pd.DataFrame(diffs))}

## Over/under 2.5 goals

{table(pd.DataFrame(ou_rows))}

## Leakage red flag

Dixon-Coles top-pick accuracy: {top_pick:.1%}. \
{'ABOVE 60%: STOP AND HUNT FOR LEAKAGE.' if red_flag else 'Below the 60% red-flag line.'}

## Per league and season

{chr(10).join(chr(10) + s + chr(10) for s in sections)}

## Tuning grid (mean RPS on the tuning seasons)

{table(grid.fillna(''))}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(text)
    return 1 if red_flag else 0


if __name__ == "__main__":
    sys.exit(main())
